apiVersion: skaffold/v4beta9
kind: Config
metadata:
  name: cloud-run-lab

build:
  artifacts:
    - image: us-central1-docker.pkg.dev/YOUR_PROJECT_ID/lab-repo/app-prod
      context: ./app
      docker:
        dockerfile: Dockerfile
  googleCloudBuild:
    projectId: YOUR_PROJECT_ID
    timeout: 600s

deploy:
  cloudrun:
    projectid: YOUR_PROJECT_ID
    region: us-central1

manifests:
  rawYaml:
    - resources/prod/service.prod.yaml

profiles:
  - name: prod
    activation:
      - command: run
    build:
      artifacts:
        - image: us-central1-docker.pkg.dev/YOUR_PROJECT_ID/lab-repo/app-prod
          context: ./app
          docker:
            dockerfile: Dockerfile
      googleCloudBuild:
        projectId: YOUR_PROJECT_ID
        timeout: 600s
    deploy:
      cloudrun:
        projectid: YOUR_PROJECT_ID
        region: us-central1
    manifests:
      rawYaml:
        - resources/prod/service.prod.yaml
